import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
const release=await import('../src/services/productionReleaseIntegrityService');
const { getSystemConfig }=await import('../src/services/configService');
const { brokerRegistry }=await import('../src/brokers/registry');
const { runtimeLifecycle }=await import('../src/services/runtimeLifecycle');
const { autoTradingService }=await import('../src/services/autoTradingService');

const scenarios:Array<{id:number;name:string;run:()=>void|Promise<void>}>=[];
const add=(id:number,name:string,run:()=>void|Promise<void>)=>scenarios.push({id,name,run});
const root=fs.mkdtempSync(path.join(os.tmpdir(),'goldcrest-phase8-15-'));
const dist=path.join(root,'dist'); const data=path.join(root,'data');
fs.mkdirSync(dist,{recursive:true}); fs.mkdirSync(data,{recursive:true});
fs.writeFileSync(path.join(dist,'server.cjs'),'server'); fs.writeFileSync(path.join(dist,'index.html'),'index');
const input=()=>({environment:'production',nodeVersion:'24.21.0',tradingMode:'LIVE_ONLY',operatorAuthConfigured:true,liveBrokerConfigured:true,distServerFile:path.join(dist,'server.cjs'),distIndexFile:path.join(dist,'index.html'),dataDirectory:data,packageVersion:'8.15-test'});
add(1,'Valid release is accepted',()=>assert.equal(release.evaluateProductionReleaseIntegrity(input()).ok,true));
add(2,'Production environment is enforced',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),environment:'development'}).ok,false));
add(3,'LIVE_ONLY is enforced',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),tradingMode:'PAPER'}).ok,false));
add(4,'Operator authentication is enforced',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),operatorAuthConfigured:false}).ok,false));
add(5,'LIVE broker configuration is enforced',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),liveBrokerConfigured:false}).ok,false));
add(6,'Node 24 is accepted',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),nodeVersion:'24.21.0'}).ok,true));
add(7,'Node 23 is rejected',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),nodeVersion:'23.21.0'}).ok,false));
add(8,'Malformed Node version is rejected',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),nodeVersion:'x'}).ok,false));
add(9,'Server bundle is required',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),distServerFile:path.join(dist,'missing')}).ok,false));
add(10,'SPA artifact is required',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),distIndexFile:path.join(dist,'missing')}).ok,false));
add(11,'Writable data directory is required',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),dataDirectory:path.join(root,'new-data')}).ok,true));
add(12,'Release version is required',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),packageVersion:''}).ok,false));
add(13,'Whitespace release version is rejected',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),packageVersion:'   '}).ok,false));
add(14,'Failure names are explicit',()=>assert.deepEqual(release.evaluateProductionReleaseIntegrity({...input(),tradingMode:'PAPER',packageVersion:''}).failures,['tradingMode','packageVersion']));
add(15,'PASS checks are enumerable',()=>assert.ok(Object.values(release.evaluateProductionReleaseIntegrity(input()).checks).every(v=>v==='PASS')));
add(16,'FAIL checks are enumerable',()=>assert.ok(Object.values(release.evaluateProductionReleaseIntegrity({...input(),tradingMode:'PAPER'}).checks).includes('FAIL')));
add(17,'Release version preserves supplied value',()=>assert.equal(release.evaluateProductionReleaseIntegrity(input()).version,'8.15-test'));
add(18,'Release evaluation is deterministic',()=>assert.deepEqual(release.evaluateProductionReleaseIntegrity(input()),release.evaluateProductionReleaseIntegrity(input())));
add(19,'Installed application version is discoverable',()=>assert.ok(release.getInstalledApplicationVersion().length>0));
add(20,'Installed application version matches package metadata',()=>{const a=release.getInstalledApplicationVersion();const p=JSON.parse(fs.readFileSync(path.join(process.cwd(),'package.json'),'utf8'));assert.equal(a,p.version);});
add(21,'Builder resolves current application version when env override is absent',()=>{const old=process.env.GOLDCREST_RELEASE_VERSION;delete process.env.GOLDCREST_RELEASE_VERSION;try{const b=release.buildProductionReleaseIntegrityInput({rootDirectory:process.cwd(),tradingMode:'LIVE_ONLY',operatorAuthConfigured:true,liveBrokerConfigured:true});assert.equal(b.packageVersion,release.getInstalledApplicationVersion());}finally{process.env.GOLDCREST_RELEASE_VERSION=old;}});
add(22,'Builder honors explicit release version override',()=>{const old=process.env.GOLDCREST_RELEASE_VERSION;process.env.GOLDCREST_RELEASE_VERSION='override-8.15';try{const b=release.buildProductionReleaseIntegrityInput({rootDirectory:root,tradingMode:'LIVE_ONLY',operatorAuthConfigured:true,liveBrokerConfigured:true});assert.equal(b.packageVersion,'override-8.15');}finally{process.env.GOLDCREST_RELEASE_VERSION=old;}});
add(23,'Builder targets production server bundle',()=>assert.equal(release.buildProductionReleaseIntegrityInput({...input(),packageVersion:undefined,rootDirectory:root}).distServerFile,path.join(root,'dist','server.cjs')));
add(24,'Builder targets production SPA bundle',()=>assert.equal(release.buildProductionReleaseIntegrityInput({...input(),packageVersion:undefined,rootDirectory:root}).distIndexFile,path.join(root,'dist','index.html')));
add(25,'Builder targets durable data directory',()=>assert.equal(release.buildProductionReleaseIntegrityInput({...input(),packageVersion:undefined,rootDirectory:root}).dataDirectory,path.join(root,'data')));
add(26,'Builder preserves LIVE_ONLY mode',()=>assert.equal(release.buildProductionReleaseIntegrityInput({...input(),packageVersion:undefined,rootDirectory:root}).tradingMode,'LIVE_ONLY'));
add(27,'Builder preserves operator state',()=>assert.equal(release.buildProductionReleaseIntegrityInput({...input(),packageVersion:undefined,rootDirectory:root}).operatorAuthConfigured,true));
add(28,'Builder preserves broker state',()=>assert.equal(release.buildProductionReleaseIntegrityInput({...input(),packageVersion:undefined,rootDirectory:root}).liveBrokerConfigured,true));
add(29,'Healthy release has no failures',()=>assert.equal(release.evaluateProductionReleaseIntegrity(input()).failures.length,0));
add(30,'Broken release is not healthy',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),distServerFile:path.join(dist,'missing')}).ok,false));

add(31,'System trading mode is LIVE_ONLY',()=>assert.equal(getSystemConfig().tradingMode,'LIVE_ONLY'));
add(32,'Broker registry is LIVE environment',()=>assert.equal(brokerRegistry.getEnvironment(),'LIVE'));
add(33,'Only LIVE adapters are active',()=>assert.ok(brokerRegistry.getActiveLiveAdapters().every(a=>a.environment==='LIVE')));
add(34,'Active adapters report live accounts',()=>assert.ok(brokerRegistry.getActiveLiveAdapters().every(a=>a.isLive===true)));
add(35,'Runtime lifecycle exposes a valid state',()=>assert.ok(['STARTING','RUNNING','DEGRADED','STOPPING','STOPPED'].includes(runtimeLifecycle.getStatus().state)));
add(36,'Auto Live state is observable',()=>assert.equal(typeof autoTradingService.getStatus().state,'string'));
add(37,'Auto Live is not autonomous by default in test baseline',()=>{autoTradingService.stop('PHASE8_15');assert.equal(autoTradingService.getStatus().autonomousPermission,false);});
add(38,'Auto Live stop preserves stopped state',()=>{autoTradingService.stop('PHASE8_15');assert.equal(autoTradingService.getStatus().state,'STOPPED');});
add(39,'Auto Live runtime fault metadata is clear after stop',()=>assert.equal(autoTradingService.getStatus().runtimeFaultReason,null));
add(40,'Auto Live pairs remain configured as an array',()=>assert.ok(Array.isArray(autoTradingService.getStatus().pairs)));

add(41,'Production release rejects non-LIVE mode even with valid artifacts',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),tradingMode:'DEMO'}).ok,false));
add(42,'Production release rejects missing credentials even with valid artifacts',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),liveBrokerConfigured:false}).ok,false));
add(43,'Production release rejects missing operator auth even with valid artifacts',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),operatorAuthConfigured:false}).ok,false));
add(44,'Production release rejects old Node even with valid artifacts',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),nodeVersion:'20.0.0'}).ok,false));
add(45,'Production release rejects missing server artifact',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),distServerFile:path.join(root,'none')}).ok,false));
add(46,'Production release rejects missing index artifact',()=>assert.equal(release.evaluateProductionReleaseIntegrity({...input(),distIndexFile:path.join(root,'none')}).ok,false));
add(47,'Production release accepts nested writable data path',()=>{const nested=path.join(root,'nested','data');assert.equal(release.evaluateProductionReleaseIntegrity({...input(),dataDirectory:nested}).ok,true);assert.equal(fs.existsSync(nested),true);});
add(48,'Production release reports exact failed artifact name',()=>{const r=release.evaluateProductionReleaseIntegrity({...input(),distIndexFile:path.join(root,'none')});assert.deepEqual(r.failures,['distIndex']);});
add(49,'Production release can report several failures together',()=>{const r=release.evaluateProductionReleaseIntegrity({...input(),nodeVersion:'20',tradingMode:'PAPER',operatorAuthConfigured:false});assert.ok(r.failures.includes('nodeVersion')&&r.failures.includes('tradingMode')&&r.failures.includes('operatorAuth'));});
add(50,'Production release does not report unrelated failure for valid broker flag',()=>{const r=release.evaluateProductionReleaseIntegrity({...input(),operatorAuthConfigured:false});assert.equal(r.checks.liveBroker,'PASS');});
add(51,'Production release does not report unrelated failure for valid auth flag',()=>{const r=release.evaluateProductionReleaseIntegrity({...input(),liveBrokerConfigured:false});assert.equal(r.checks.operatorAuth,'PASS');});
add(52,'Current package version is non-empty',()=>assert.ok(release.getInstalledApplicationVersion().trim().length>0));
add(53,'Current package version is stable across two reads',()=>assert.equal(release.getInstalledApplicationVersion(),release.getInstalledApplicationVersion()));
add(54,'Release integrity version override does not mutate package metadata',()=>{const p=release.getInstalledApplicationVersion();const r=release.evaluateProductionReleaseIntegrity({...input(),packageVersion:'temporary'});assert.equal(release.getInstalledApplicationVersion(),p);assert.equal(r.version,'temporary');});
add(55,'Data directory check is independent of broker check',()=>{const r=release.evaluateProductionReleaseIntegrity({...input(),dataDirectory:path.join(root,'no-broker-impact')});assert.equal(r.checks.liveBroker,'PASS');});
add(56,'Server artifact check is independent of data path',()=>{const r=release.evaluateProductionReleaseIntegrity({...input(),distServerFile:path.join(dist,'missing')});assert.equal(r.checks.dataDirectoryWritable,'PASS');});
add(57,'Index artifact check is independent of Node check',()=>{const r=release.evaluateProductionReleaseIntegrity({...input(),distIndexFile:path.join(dist,'missing')});assert.equal(r.checks.nodeVersion,'PASS');});
add(58,'Environment check is independent of artifacts',()=>{const r=release.evaluateProductionReleaseIntegrity({...input(),environment:'production'});assert.equal(r.checks.distServer,'PASS');assert.equal(r.checks.distIndex,'PASS');});
add(59,'LIVE_ONLY boundary survives final release checks',()=>{assert.equal(getSystemConfig().tradingMode,'LIVE_ONLY');assert.equal(release.evaluateProductionReleaseIntegrity(input()).checks.tradingMode,'PASS');});
add(60,'Final launch certification remains fail-closed',()=>{const r=release.evaluateProductionReleaseIntegrity({...input(),operatorAuthConfigured:false,liveBrokerConfigured:false,packageVersion:''});assert.equal(r.ok,false);assert.ok(r.failures.length>=3);});

console.log('=========================================================================');
console.log('PHASE 8.15 — FINAL PRODUCTION LAUNCH READINESS CERTIFICATION');
console.log('60 deterministic, broker-side-effect-free launch scenarios');
console.log('=========================================================================');
assert.equal(scenarios.length,60);
for(const item of scenarios){item.run();console.log('[PASS '+String(item.id).padStart(2,'0')+'/60] '+item.name);}
console.log('=========================================================================');
console.log('PHASE 8.15 CERTIFICATION: 60/60 PASSED');
console.log('Production release metadata: VERIFIED');
console.log('Deployment artifact integrity: VERIFIED');
console.log('Fail-closed launch contract: VERIFIED');
console.log('LIVE_ONLY boundary: VERIFIED');
console.log('Operator authentication boundary: VERIFIED');
console.log('Autonomous live execution: NOT ENABLED');
console.log('Broker order submission: NOT INVOKED');
console.log('=========================================================================');
fs.rmSync(root,{recursive:true,force:true});