import { executeQuery } from '../database/db';
import type { CurrentPairPredictionHorizon } from './currentPairPredictionOutcomeService';
const MIN_SAMPLE_COUNT=30,BASELINE_MODEL='PAIR_FEATURE_BASELINE_V2',AI_MODEL='LLAMA_GATEWAY_QWEN_LLAMA_V1';
type Metrics={predictions:number;directionalEvaluated:number;correct:number;accuracyPct:number|null;averageConfidencePct:number|null;expectedCalibrationErrorPct:number|null;calibrationSlope:number|null;sampleSufficient:boolean};
export interface CurrentPairCrossModelContextCalibrationRow{symbol:string;horizon:CurrentPairPredictionHorizon;marketRegime:string;session:string;pairedObservations:number;pairedEvaluated:number;pairedPending:number;baseline:{modelVersion:string;metrics:Metrics};ai:{modelVersion:string;metrics:Metrics};deltas:{accuracyDeltaPct:number|null;confidenceDeltaPct:number|null;expectedCalibrationErrorDeltaPct:number|null;calibrationSlopeDelta:number|null}};
const empty=():Metrics=>({predictions:0,directionalEvaluated:0,correct:0,accuracyPct:null,averageConfidencePct:null,expectedCalibrationErrorPct:null,calibrationSlope:null,sampleSufficient:false});
function metric(rows:any[]):Metrics{const r=empty(),b=Array.from({length:5},()=>({n:0,e:0,c:0,cs:0})),obs:{x:number;y:number}[]=[];r.predictions=rows.length;for(const row of rows){const x=Math.max(0,Math.min(1,Number(row.confidence)||0)),k=b[Math.min(4,Math.floor(x*100/20))];k.n++;k.cs+=x;if(row.outcome_status!=='EVALUATED'||!row.actual_direction||row.predicted_direction==='FLAT'||row.actual_direction==='FLAT')continue;const y=row.predicted_direction===row.actual_direction?1:0;r.directionalEvaluated++;r.correct+=y;k.e++;k.c+=y;obs.push({x,y});}r.accuracyPct=r.directionalEvaluated?r.correct/r.directionalEvaluated*100:null;r.averageConfidencePct=r.predictions?rows.reduce((s,x)=>s+Math.max(0,Math.min(1,Number(x.confidence)||0)),0)/r.predictions*100:null;if(r.directionalEvaluated){r.expectedCalibrationErrorPct=b.filter(x=>x.e).reduce((s,x)=>s+Math.abs(x.cs/x.n*100-x.c/x.e*100)*x.e/r.directionalEvaluated,0);if(r.directionalEvaluated>=MIN_SAMPLE_COUNT){const mx=obs.reduce((s,o)=>s+o.x,0)/obs.length,my=obs.reduce((s,o)=>s+o.y,0)/obs.length,v=obs.reduce((s,o)=>s+(o.x-mx)**2,0);r.calibrationSlope=v>Number.EPSILON?obs.reduce((s,o)=>s+(o.x-mx)*(o.y-my),0)/v:null;}}r.sampleSufficient=r.directionalEvaluated>=MIN_SAMPLE_COUNT;return r;}
const delta=(a:number|null,b:number|null)=>a==null||b==null?null:a-b;
function context(row:any,f:'marketRegime'|'session'){try{const v=JSON.parse(row.feature_snapshot_json||'{}')?.[f];return typeof v==='string'&&v.trim()?v.trim().toUpperCase():'UNKNOWN';}catch{return'UNKNOWN';}}
export async function getCurrentPairCrossModelContextCalibration(p:{symbol?:string;horizon?:CurrentPairPredictionHorizon;marketRegime?:string;session?:string;now?:number}={}){
 const now=Number(p.now)||Date.now(),from=now-120*86400000,c=["prediction_context='CURRENT_PAIR'",'model_version IN (?,?)','predicted_at>=?','predicted_at<=?'],v:any[]=[BASELINE_MODEL,AI_MODEL,from,now];if(p.symbol){c.push('symbol=?');v.push(p.symbol.toUpperCase());}if(p.horizon){c.push('horizon=?');v.push(p.horizon);}
 const rows=await executeQuery<any>(`SELECT model_version,symbol,horizon,predicted_at,predicted_direction,confidence,actual_direction,outcome_status,feature_snapshot_json FROM live_trade_research_predictions WHERE ${c.join(' AND ')} ORDER BY predicted_at ASC`,v);
 const pairs=new Map<string,{b?:any;a?:any}>();for(const row of rows){const key=`${String(row.symbol).trim().toUpperCase()}|${String(row.horizon).toUpperCase()}|${context(row,'marketRegime')}|${context(row,'session')}|${Number(row.predicted_at)}`;const x=pairs.get(key)||{};if(row.model_version===BASELINE_MODEL&&!x.b)x.b=row;if(row.model_version===AI_MODEL&&!x.a)x.a=row;pairs.set(key,x);}
 const groups=new Map<string,any[]>();for(const[key,x]of pairs){if(!x.b||!x.a)continue;const[s,h,r,se]=key.split('|');if(p.marketRegime&&r!==p.marketRegime.toUpperCase())continue;if(p.session&&se!==p.session.toUpperCase())continue;const g=groups.get(`${s}|${h}|${r}|${se}`)||[];g.push({b:x.b,a:x.a});groups.set(`${s}|${h}|${r}|${se}`,g);}
 const out:CurrentPairCrossModelContextCalibrationRow[]=[];for(const[key,g]of groups){const[s,h,r,se]=key.split('|'),valid=(x:any)=>x.outcome_status==='EVALUATED'&&x.actual_direction&&x.predicted_direction!=='FLAT'&&x.actual_direction!=='FLAT',pe=g.filter(x=>valid(x.b)&&valid(x.a)).length,bm=metric(g.map(x=>x.b)),am=metric(g.map(x=>x.a));out.push({symbol:s,horizon:h as CurrentPairPredictionHorizon,marketRegime:r,session:se,pairedObservations:g.length,pairedEvaluated:pe,pairedPending:g.length-pe,baseline:{modelVersion:BASELINE_MODEL,metrics:bm},ai:{modelVersion:AI_MODEL,metrics:am},deltas:{accuracyDeltaPct:delta(am.accuracyPct,bm.accuracyPct),confidenceDeltaPct:delta(am.averageConfidencePct,bm.averageConfidencePct),expectedCalibrationErrorDeltaPct:delta(am.expectedCalibrationErrorPct,bm.expectedCalibrationErrorPct),calibrationSlopeDelta:delta(am.calibrationSlope,bm.calibrationSlope)}});}
 out.sort((a,b)=>a.symbol.localeCompare(b.symbol)||a.horizon.localeCompare(b.horizon)||a.marketRegime.localeCompare(b.marketRegime)||a.session.localeCompare(b.session));return{baselineModelVersion:BASELINE_MODEL,aiModelVersion:AI_MODEL,minimumSampleCount:MIN_SAMPLE_COUNT,generatedAt:now,rows:out};
}